//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberListGifts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityPresent_Log
    {
        public long Id { get; set; }
        public string MemberId { get; set; }
        public string MallId { get; set; }
        public Nullable<int> GId { get; set; }
        public string CouponNo { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public Nullable<int> ModifyUser { get; set; }
        public string UsedMallId { get; set; }
        public string UsedDepartment { get; set; }
        public string Remark { get; set; }
    }
}
