//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberListGifts.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GiftsEntities : DbContext
    {
        public GiftsEntities()
            : base("name=GiftsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EntityPresent> EntityPresent { get; set; }
        public virtual DbSet<SystemErrorLog> SystemErrorLog { get; set; }
        public virtual DbSet<UsedRule> UsedRule { get; set; }
        public virtual DbSet<Giftss> Gifts { get; set; }
        public virtual DbSet<ExchangeLog> ExchangeLog { get; set; }
        public virtual DbSet<EntityPresent_Log> EntityPresent_Log { get; set; }
    }
}
